In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("facebook.csv", sep=';')
data

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [6]:
subset1 = data[["Type", "comment", "like", "share"]]
subset2 = data[["Type", "Post Month", "Post Weekday", "Post Hour"]]
print(subset1)
print(subset2)

       Type  comment    like  share
0     Photo        4    79.0   17.0
1    Status        5   130.0   29.0
2     Photo        0    66.0   14.0
3     Photo       58  1572.0  147.0
4     Photo       19   325.0   49.0
..      ...      ...     ...    ...
495   Photo        5    53.0   26.0
496   Photo        0    53.0   22.0
497   Photo        4    93.0   18.0
498   Photo        7    91.0   38.0
499   Photo        0    91.0   28.0

[500 rows x 4 columns]
       Type  Post Month  Post Weekday  Post Hour
0     Photo          12             4          3
1    Status          12             3         10
2     Photo          12             3          3
3     Photo          12             2         10
4     Photo          12             2          3
..      ...         ...           ...        ...
495   Photo           1             7          2
496   Photo           1             5          8
497   Photo           1             5          2
498   Photo           1             4         11
499   Photo           1             4          4

[500 rows x 4 columns]

In [33]:
subset3 = data.loc[0:5, ["Type", "comment", "like"]]
subset3
subset4 = data.iloc[0:5,[0,1]]
subset4

   Page total likes    Type
0            139441   Photo
1            139441  Status
2            139441   Photo
3            139441   Photo
4            139441   Photo

In [9]:
merged_data = subset1.merge(subset2, on='Type', how='left')
print(merged_data)

         Type  comment  like  share  Post Month  Post Weekday  Post Hour
0       Photo        4  79.0   17.0          12             4          3
1       Photo        4  79.0   17.0          12             3          3
2       Photo        4  79.0   17.0          12             2         10
3       Photo        4  79.0   17.0          12             2          3
4       Photo        4  79.0   17.0          12             1          3
...       ...      ...   ...    ...         ...           ...        ...
184029  Photo        0  91.0   28.0           1             7          2
184030  Photo        0  91.0   28.0           1             5          8
184031  Photo        0  91.0   28.0           1             5          2
184032  Photo        0  91.0   28.0           1             4         11
184033  Photo        0  91.0   28.0           1             4          4

[184034 rows x 7 columns]

In [11]:
merged_data = pd.concat([subset1, subset2], axis=1)
print(merged_data)

       Type  comment    like  share    Type  Post Month  Post Weekday  \
0     Photo        4    79.0   17.0   Photo          12             4
1    Status        5   130.0   29.0  Status          12             3
2     Photo        0    66.0   14.0   Photo          12             3
3     Photo       58  1572.0  147.0   Photo          12             2
4     Photo       19   325.0   49.0   Photo          12             2
..      ...      ...     ...    ...     ...         ...           ...
495   Photo        5    53.0   26.0   Photo           1             7
496   Photo        0    53.0   22.0   Photo           1             5
497   Photo        4    93.0   18.0   Photo           1             5
498   Photo        7    91.0   38.0   Photo           1             4
499   Photo        0    91.0   28.0   Photo           1             4

     Post Hour
0            3
1           10
2            3
3           10
4            3
..         ...
495          2
496          8
497          2
498         11
499          4

[500 rows x 8 columns]

In [29]:
sorted_data = merged_data.sort_values(by="like", ascending=False, ignore_index=True)
sorted_data

      Type  comment    like  share   Type  Post Month  Post Weekday  Post Hour
0    Photo      372  5172.0  790.0  Photo           7             3          5
1    Photo       51  1998.0  128.0  Photo           4             1         14
2    Photo       45  1639.0  122.0  Photo           5             5         13
3    Photo      144  1622.0  208.0  Photo           9             3         10
4    Photo       58  1572.0  147.0  Photo          12             2         10
..     ...      ...     ...    ...    ...         ...           ...        ...
495  Photo        0     0.0    0.0  Photo          10             4          9
496  Photo        0     0.0    0.0  Photo           3             3         10
497  Photo        0     0.0    0.0  Photo           3             5          4
498  Photo        0     0.0    0.0  Photo          12             7         10
499  Photo        0     NaN    NaN  Photo          10             6          8

[500 rows x 8 columns]

In [31]:
concat = pd.concat([subset3, subset4], axis=0)
concat

   comment    like  Page total likes    Type
0      4.0    79.0               NaN     NaN
1      5.0   130.0               NaN     NaN
2      0.0    66.0               NaN     NaN
3     58.0  1572.0               NaN     NaN
4     19.0   325.0               NaN     NaN
5      1.0   152.0               NaN     NaN
0      NaN     NaN          139441.0   Photo
1      NaN     NaN          139441.0  Status
2      NaN     NaN          139441.0   Photo
3      NaN     NaN          139441.0   Photo
4      NaN     NaN          139441.0   Photo

In [37]:
transposed_data = sorted_data.transpose()
print(transposed_data);

                 0       1       2       3       4       5       6       7    \
Type           Photo   Photo   Photo   Photo   Photo   Photo   Photo   Photo
comment          372      51      45     144      58     146      26      20
like          5172.0  1998.0  1639.0  1622.0  1572.0  1546.0  1505.0  1372.0
share          790.0   128.0   122.0   208.0   147.0   181.0    95.0    47.0
Type           Photo   Photo   Photo   Photo   Photo   Photo   Photo   Photo
Post Month         7       4       5       9      12       2      10       6
Post Weekday       3       1       5       3       2       1       4       1
Post Hour          5      14      13      10      10      13       3      10

                 8       9    ...    490    491    492    493    494    495  \
Type           Photo   Photo  ...  Photo  Photo  Photo  Photo  Photo  Photo
comment           33      29  ...      0      0      0      1      0      0
like          1155.0  1047.0  ...    2.0    2.0    2.0    1.0    0.0    0.0
share          102.0    98.0  ...    0.0    NaN    0.0    2.0    0.0    0.0
Type           Photo   Photo  ...  Photo  Photo  Photo  Photo  Photo  Photo
Post Month         8       9  ...      3     10      3     10     11     10
Post Weekday       4       6  ...      1      7      7      7      3      4
Post Hour         10       3  ...     19      9     15      8      2      9

                496    497    498    499
Type          Photo  Photo  Photo  Photo
comment           0      0      0      0
like            0.0    0.0    0.0    NaN
share           0.0    0.0    0.0    NaN
Type          Photo  Photo  Photo  Photo
Post Month        3      3     12     10
Post Weekday      3      5      7      6
Post Hour        10      4     10      8

[8 rows x 500 columns]

In [38]:
data.shape

(500, 19)

In [39]:
transposed_data.shape

(8, 500)

In [42]:
data = np.array(data[["comment", "like"]].head(6))
data.shape

(6, 2)

In [44]:
reshaped_data = data.reshape(3,4)
reshaped_data.shape

(3, 4)